name: Test Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        nginx-branch: [stable, mainline]
    steps:
      - uses: actions/checkout@v3

      - name: Install build and test dependencies
        run: |
          sudo apt-get --yes update
          sudo apt-get install --yes libipset-dev ipset libpcre3-dev libssl-dev perl cpanminus wget

      - name: Create NGINX download directory
        run: |
          mkdir nginx

      - name: Download ${{ matrix.nginx-branch }} NGINX
        uses: dvershinin/lastversion-action@main
        with:
          repository: 'nginx'
          action: 'unzip'
          branch: ${{ matrix.nginx-branch }}
          working_directory: ./nginx

      - name: Configure NGINX to compile with the module statically
        run: |
          cd nginx && ./configure --with-debug --add-module=..

      - name: Make NGINX
        run: |
          cd nginx && make -j$(nproc)
